### ISSUE TITLE
Some lift shafts don't work.

### ISSUE THREAD

**Issue by gpcf** [Splizard/minetest-mod-lifter#4]
I have a lift shaft that looks like this:

```
X X X
X - X
X X X
```

All sides are covered with air at some point.
When I try to open the door, it fails saying "too much air". I modified it to look like this:

```
X X X X
X - X X
X X X X
```

Adding just that one wall makes the lift work. I don't know what causes this.

**Comment by Splizard** [comment]
Ah, that will be due to this part of code

```
local test = minetest.find_nodes_in_area({x=pos.x-2, y=pos.y+i, z=pos.z-2}, {x=pos.x+2, y=pos.y+i, z=pos.z+2}, "air")
            if #test == 16 then
                print("lift not found, too much air")
                return
            end
```

Changing that to

```
local test = minetest.find_nodes_in_area({x=pos.x-1, y=pos.y+i, z=pos.z-1}, {x=pos.x+1, y=pos.y+i, z=pos.z+1}, "air")
            if #test == 9 then
                print("lift not found, too much air")
                return
            end
```

Should do the trick, although I can't test this at the moment.

**Comment by gpcf** [comment]
I'll test it, wait a sec.

**Comment by gpcf** [comment]
I've added your bugfix (#5).
